language: go
sudo: false
go:
- 1.20.x
- 1.18.x
go_import_path: github.com/nats-io/graft

install:
- go get -t ./...
- go get github.com/nats-io/nats-server/v2
- go get github.com/mattn/goveralls
- go get github.com/wadey/gocovmerge

script:
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...
  - go test -v -race ./...
  - ./scripts/cov.sh TRAVIS
